root: true
env:
  browser: true
  es6: true
  node: true
extends:
  - standard
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/standard'
  - 'prettier/react'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
